"""empty message

Revision ID: 1c933f30e6cf
Revises: 6eec1832daab
Create Date: 2018-04-13 22:59:42.057119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c933f30e6cf'
down_revision = '6eec1832daab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'order', ['OrderId'])
    op.drop_constraint('order_ibfk_2', 'order', type_='foreignkey')
    op.drop_index('OrderId', table_name='send')
    op.create_foreign_key(None, 'send', 'order', ['OrderId'], ['OrderId'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'send', type_='foreignkey')
    op.create_index('OrderId', 'send', ['OrderId'], unique=True)
    op.create_foreign_key('order_ibfk_2', 'order', 'send', ['OrderId'], ['OrderId'])
    op.drop_constraint(None, 'order', type_='unique')
    # ### end Alembic commands ###
