"""empty message

Revision ID: be105fb8a51e
Revises: 
Create Date: 2018-04-14 17:28:47.306254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be105fb8a51e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('custom',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('CustomId', sa.String(length=30), nullable=True),
    sa.Column('CustomName', sa.String(length=30), nullable=True),
    sa.Column('CustomPhone', sa.String(length=30), nullable=True),
    sa.Column('CustomAddress', sa.String(length=100), nullable=True),
    sa.Column('CustomAccount', sa.String(length=30), nullable=True),
    sa.Column('CustomType', sa.String(length=30), nullable=True),
    sa.Column('CustomConsume', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('CustomId')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ProductId', sa.String(length=30), nullable=True),
    sa.Column('ProductName', sa.String(length=30), nullable=True),
    sa.Column('ProducerName', sa.String(length=30), nullable=True),
    sa.Column('ProductDate', sa.Date(), nullable=True),
    sa.Column('ProductType', sa.String(length=30), nullable=True),
    sa.Column('ProductPrice', sa.String(length=30), nullable=True),
    sa.Column('ProductNum', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ProductId')
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('OrderId', sa.String(length=30), nullable=True),
    sa.Column('CustomId', sa.String(length=30), nullable=True),
    sa.Column('ProductId', sa.String(length=30), nullable=True),
    sa.Column('OrderNum', sa.String(length=30), nullable=True),
    sa.Column('OrderDate', sa.Date(), nullable=True),
    sa.Column('OrderStatus', sa.String(length=30), nullable=True),
    sa.Column('OrderMoney', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['CustomId'], ['custom.CustomId'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('OrderId')
    )
    op.create_table('serve',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ServeId', sa.String(length=30), nullable=True),
    sa.Column('CustomId', sa.String(length=30), nullable=False),
    sa.Column('ServeDate', sa.Date(), nullable=True),
    sa.Column('ServeInfo', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['CustomId'], ['custom.CustomId'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('po',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('order_id', 'product_id')
    )
    op.create_table('send',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('OrderId', sa.String(length=30), nullable=True),
    sa.Column('ProductName', sa.String(length=30), nullable=True),
    sa.Column('SendName', sa.String(length=30), nullable=True),
    sa.Column('SendDate', sa.Date(), nullable=True),
    sa.Column('SendPhone', sa.String(length=30), nullable=True),
    sa.Column('SendAddress', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['OrderId'], ['order.OrderId'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('send')
    op.drop_table('po')
    op.drop_table('serve')
    op.drop_table('order')
    op.drop_table('product')
    op.drop_table('custom')
    op.drop_table('admin')
    # ### end Alembic commands ###
