"""empty message

Revision ID: cc47c965f137
Revises: 72bda7293f67
Create Date: 2018-04-12 21:32:07.293550

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cc47c965f137'
down_revision = '72bda7293f67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('passworld', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('custom',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('CustomId', sa.String(length=30), nullable=False),
    sa.Column('CustomName', sa.String(length=30), nullable=True),
    sa.Column('CustomPhone', sa.String(length=30), nullable=True),
    sa.Column('CustomAddress', sa.String(length=100), nullable=True),
    sa.Column('CustomAccount', sa.String(length=30), nullable=True),
    sa.Column('CustomType', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('CustomId')
    )
    op.create_table('send',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ProductId', sa.String(length=30), nullable=False),
    sa.Column('ProductName', sa.String(length=30), nullable=True),
    sa.Column('SendName', sa.String(length=30), nullable=True),
    sa.Column('SendDate', sa.Date(), nullable=True),
    sa.Column('SendPhone', sa.String(length=30), nullable=True),
    sa.Column('SendAddress', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ProductId')
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('OrderId', sa.String(length=30), nullable=True),
    sa.Column('CustomId', sa.String(length=30), nullable=True),
    sa.Column('ProductId', sa.String(length=30), nullable=True),
    sa.Column('OrderName', sa.String(length=30), nullable=True),
    sa.Column('OrderDate', sa.Date(), nullable=True),
    sa.Column('OrderStatus', sa.String(length=30), nullable=True),
    sa.Column('OrderMoney', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['CustomId'], ['custom.CustomId'], ),
    sa.ForeignKeyConstraint(['ProductId'], ['send.ProductId'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ProductId')
    )
    op.create_table('serve',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ServeId', sa.String(length=30), nullable=True),
    sa.Column('CustomId', sa.String(length=30), nullable=False),
    sa.Column('ServeDate', sa.Date(), nullable=True),
    sa.Column('ServeInfo', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['CustomId'], ['custom.CustomId'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ProductId', sa.String(length=30), nullable=False),
    sa.Column('ProductName', sa.String(length=30), nullable=True),
    sa.Column('ProducerName', sa.String(length=30), nullable=True),
    sa.Column('ProductDate', sa.Date(), nullable=True),
    sa.Column('ProductType', sa.String(length=30), nullable=True),
    sa.Column('ProductPrice', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['ProductId'], ['order.ProductId'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('username', mysql.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('product')
    op.drop_table('serve')
    op.drop_table('order')
    op.drop_table('send')
    op.drop_table('custom')
    op.drop_table('admin')
    # ### end Alembic commands ###
