"""empty message

Revision ID: e5c26ad376ba
Revises: eac9d62466f0
Create Date: 2018-04-14 15:49:43.916962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5c26ad376ba'
down_revision = 'eac9d62466f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom', sa.Column('CustomConsume', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('custom', 'CustomConsume')
    # ### end Alembic commands ###
