"""empty message

Revision ID: eac9d62466f0
Revises: 1c933f30e6cf
Create Date: 2018-04-14 13:45:46.398613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eac9d62466f0'
down_revision = '1c933f30e6cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('ProductNum', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'ProductNum')
    # ### end Alembic commands ###
